server:
  port: ${SOCKET_PORT}
  tomcat:
    threads:
      max: 4
spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}

etterna:
  login:
    provider-class: ${LOGIN_PROVIDER_CLASS}
    api-url: ${LOGIN_API_URL}
    api-key: ${LOGIN_API_KEY}

discord:
  token: ${DISCORD_TOKEN}
  webhook: ${DISCORD_WEBHOOK}
  channelid: ${DISCORD_CHANNELID}
    
logging:
  level:
    #org.hibernate.SQL: DEBUG
    com.etterna: DEBUG
